import { db } from '@/db/client';
import { portfolios } from '@/db/schema';
import { eq, and } from 'drizzle-orm';
import { getCurrentOrganizationContext } from '@/lib/auth/session';
import { logAuditAction, AUDIT_ACTIONS } from '@/lib/audit/logger';
import { canManagePortfolio } from '@/lib/auth/permissions';
import { z } from 'zod';


// Validation schema
//
// PF2 STATUS_INPUT_CONTRACT: no PF2 request schema may accept a `status`
// field. portfolios.status is written by exactly two authorized paths and by
// no input surface: createPortfolioForCurrentOrganization always writes the
// literal 'active', archivePortfolioForCurrentOrganization always writes the
// literal 'archived'. A caller-supplied status here would let a create reach
// the archived state with no portfolio.archived audit row anywhere in the
// trail (PF2-NEG-STATUS-1).
const PortfolioInputSchema = z.object({
  name: z.string().min(1),
  description: z.string().optional(),
});

type PortfolioInput = z.input<typeof PortfolioInputSchema>;

// Update-only fields (name/description). Status is never accepted here either
// — see PortfolioInputSchema's note above and PF2-NEG-UNARCHIVE-1.
const PortfolioUpdateInputSchema = z
  .object({
    name: z.string().min(1).optional(),
    description: z.string().optional(),
  })
  .refine((data) => data.name !== undefined || data.description !== undefined, {
    message: 'At least one of name or description must be provided',
  });

type PortfolioUpdateInput = z.input<typeof PortfolioUpdateInputSchema>;

/** List all portfolios for the current organization */
export async function listPortfoliosForCurrentOrganization() {
  const ctx = await getCurrentOrganizationContext();
  if (!ctx) throw new Error('Unauthenticated');
  return db.select().from(portfolios).where(eq(portfolios.organizationId, ctx.organization.id));
}

/** Get a portfolio by ID, scoped to the current org */
export async function getPortfolioByIdForCurrentOrganization(id: string) {
  const ctx = await getCurrentOrganizationContext();
  if (!ctx) return null;
  const rows = await db
    .select()
    .from(portfolios)
    .where(and(eq(portfolios.id, id), eq(portfolios.organizationId, ctx.organization.id)));
  return rows[0] ?? null;
}

/** Create a portfolio, verifying role and logging. Always active — see PortfolioInputSchema. */
export async function createPortfolioForCurrentOrganization(input: PortfolioInput) {
  const ctx = await getCurrentOrganizationContext();
  if (!ctx) throw new Error('Unauthenticated');
  if (!canManagePortfolio(ctx.membership.role)) {
    throw new Error('Permission denied');
  }
  const data = PortfolioInputSchema.parse(input);
  const [newRecord] = await db
    .insert(portfolios)
    .values({
      // id is generated by the column's defaultRandom() — no manual UUID, to
      // match every other service in the codebase (projects, outcomes, etc.).
      organizationId: ctx.organization.id,
      name: data.name,
      description: data.description ?? null,
      status: 'active',
      createdBy: ctx.user.id,
    })
    .returning();

  await logAuditAction({
    organizationId: ctx.organization.id,
    actorUserId: ctx.user.id,
    entityType: 'portfolio',
    entityId: newRecord.id,
    action: AUDIT_ACTIONS.PORTFOLIO_CREATED,
    afterJson: data,
  });

  return newRecord;
}

/** Update a portfolio's name and/or description. Status is never updatable through this path. */
export async function updatePortfolioForCurrentOrganization(id: string, input: PortfolioUpdateInput) {
  const ctx = await getCurrentOrganizationContext();
  if (!ctx) throw new Error('Unauthenticated');
  if (!canManagePortfolio(ctx.membership.role)) {
    throw new Error('Permission denied');
  }
  const data = PortfolioUpdateInputSchema.parse(input);

  const existing = await getPortfolioByIdForCurrentOrganization(id);
  if (!existing) throw new Error('Portfolio not found');

  const updated = await db
    .update(portfolios)
    .set({
      ...(data.name !== undefined ? { name: data.name } : {}),
      ...(data.description !== undefined ? { description: data.description } : {}),
      updatedAt: new Date(),
    })
    .where(and(eq(portfolios.id, id), eq(portfolios.organizationId, ctx.organization.id)))
    .returning();

  if (updated.length === 0) throw new Error('Failed to update portfolio');

  await logAuditAction({
    organizationId: ctx.organization.id,
    actorUserId: ctx.user.id,
    entityType: 'portfolio',
    entityId: id,
    action: AUDIT_ACTIONS.PORTFOLIO_UPDATED,
    contentModifying: true,
    beforeJson: { name: existing.name, description: existing.description },
    afterJson: data,
  });

  return updated[0];
}

/**
 * Archive a portfolio — a grouping-only transition. Never archives, deletes,
 * detaches or otherwise touches member projects: exactly one column of
 * exactly one portfolios row is written (PF2 archive.grouping_only).
 * Unarchiving is out of scope for V1 (PF2-NEG-UNARCHIVE-1) — this is the
 * ONLY writer of 'archived', and it never writes 'active'.
 */
export async function archivePortfolioForCurrentOrganization(id: string) {
  const ctx = await getCurrentOrganizationContext();
  if (!ctx) throw new Error('Unauthenticated');
  if (!canManagePortfolio(ctx.membership.role)) {
    throw new Error('Permission denied');
  }

  const existing = await getPortfolioByIdForCurrentOrganization(id);
  if (!existing) throw new Error('Portfolio not found');
  if (existing.status === 'archived') {
    throw new Error('El portafolio ya está archivado.');
  }

  const updated = await db
    .update(portfolios)
    .set({ status: 'archived', updatedAt: new Date() })
    .where(and(eq(portfolios.id, id), eq(portfolios.organizationId, ctx.organization.id)))
    .returning();

  if (updated.length === 0) throw new Error('Failed to archive portfolio');

  await logAuditAction({
    organizationId: ctx.organization.id,
    actorUserId: ctx.user.id,
    entityType: 'portfolio',
    entityId: id,
    action: AUDIT_ACTIONS.PORTFOLIO_ARCHIVED,
    contentModifying: true,
    beforeJson: { status: existing.status },
    afterJson: { status: 'archived' },
  });

  return updated[0];
}
