-- Multi-org S1 -- founder traceability (MO-10 / MO-11 / MO-01, HPO-ODS-W2-20).
-- Generated by drizzle-kit generate; the MO-11 backfill is hand-authored below.
--
-- organizations.founded_by      uuid NULL REFERENCES users(id) ON DELETE RESTRICT
--                               TRACEABILITY ONLY (PI-3). Never read by any
--                               authorization path. NULLABLE permanently.
-- organizations.founding_provenance
--                               the durable self-service DISCRIMINATOR the
--                               MO-01 carrier predicates on: 'self_service' |
--                               'platform' | 'unknown', DEFAULT 'unknown'.
-- organizations_self_service_founder_unique
--                               partial UNIQUE (founded_by) WHERE founded_by IS
--                               NOT NULL AND founding_provenance = 'self_service'
--                               -- binds the self-service founding ACT, never
--                               the column globally. NULL founded_by rows and
--                               platform-provenance rows never collide.
--
-- No CREATE TABLE. No policy, function, trigger, role, ownership or extension
-- statement. The only DML is the structural backfill at the end.

ALTER TABLE "organizations" ADD COLUMN "founded_by" uuid;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "founding_provenance" varchar(20) DEFAULT 'unknown' NOT NULL;--> statement-breakpoint
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_founded_by_users_id_fk" FOREIGN KEY ("founded_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "organizations_self_service_founder_unique" ON "organizations" USING btree ("founded_by") WHERE "organizations"."founded_by" IS NOT NULL AND "organizations"."founding_provenance" = 'self_service';--> statement-breakpoint
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_founding_provenance_check" CHECK ("organizations"."founding_provenance" IN ('self_service', 'platform', 'unknown'));--> statement-breakpoint
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_self_service_requires_founder_check" CHECK ("organizations"."founding_provenance" <> 'self_service' OR "organizations"."founded_by" IS NOT NULL);--> statement-breakpoint

-- Stage B -- MO-11 conservative, deterministic-provenance-only backfill.
-- structural-backfill: derived by SELECT from audit_logs, so on an empty
-- database it affects zero rows. Exactly ONE qualifying 'organization.created'
-- audit row with a NON-NULL actor attributes that actor; zero rows, more than
-- one row, or a NULL actor leaves founded_by NULL. founding_provenance is NOT
-- written here: every historical row keeps the column DEFAULT 'unknown'.
-- PROHIBITED and absent: invited_by IS NULL, earliest joined_at/created_at,
-- sole organization_admin, lowest id, or any "most likely founder" heuristic.
UPDATE "organizations" AS o
SET "founded_by" = q.actor_user_id
FROM (
  -- HAVING count(*) = 1 makes the group a single row; (array_agg(...))[1]
  -- is therefore THAT row's actor (PostgreSQL has no min()/max() over uuid).
  SELECT "entity_id" AS organization_id, (array_agg("actor_user_id"))[1] AS actor_user_id
  FROM "audit_logs"
  WHERE "action" = 'organization.created' AND "entity_type" = 'organization'
  GROUP BY "entity_id"
  HAVING count(*) = 1 AND count("actor_user_id") = 1
) AS q
WHERE o."id" = q.organization_id AND o."founded_by" IS NULL;
