// lib/grounding/__tests__/extract.test.ts
// U2: dependency-free extraction layer, tested against the REAL deterministic
// fixtures in audit-fixtures/agua-segura (generated by generate.mjs, fixed seed).

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import {
  extractDocument,
  MAX_GROUNDING_INPUT_BYTES,
  MAX_EXTRACTED_TEXT_CHARS,
} from '../extract'

const FIXTURES = path.resolve(process.cwd(), 'audit-fixtures', 'agua-segura')
const fixture = (name: string) => readFileSync(path.join(FIXTURES, name))

describe('extractDocument — text/csv (real fixtures)', () => {
  it('extracts linea-base.csv: banner + header + 120 data rows', () => {
    const result = extractDocument(fixture('linea-base.csv'), 'text/csv')
    expect(result.status).toBe('extracted')
    expect(result.tables).toHaveLength(1)
    const rows = result.tables[0].rows
    // 1 banner line + 1 header + 120 households
    expect(rows).toHaveLength(122)
    expect(rows[0][0]).toContain('DATOS SINTÉTICOS')
    expect(rows[1]).toEqual([
      'hogar_id',
      'sector',
      'personas',
      'horas_semana_agua',
      'gasto_mensual_cop',
      'bienestar_pct',
      'fecha_medicion',
    ])
    expect(rows[2][0]).toBe('HOG-001')
    expect(rows[121][0]).toBe('HOG-120')
    // every data row measured on baseline date
    for (const row of rows.slice(2)) {
      expect(row[6]).toBe('2025-01-15')
      expect(row).toHaveLength(7)
    }
    expect(result.text).toContain('HOG-120')
    expect(result.meta.chars).toBe(result.text.length)
    expect(result.meta.truncated).toBe(false)
    expect(result.warnings).toEqual([])
  })

  it('extracts encuesta-final.csv: 120 data rows, final survey date', () => {
    const result = extractDocument(fixture('encuesta-final.csv'), 'text/csv')
    expect(result.status).toBe('extracted')
    const rows = result.tables[0].rows
    expect(rows).toHaveLength(122)
    expect(rows[2][0]).toBe('HOG-001')
    for (const row of rows.slice(2)) expect(row[6]).toBe('2025-12-10')
  })

  it('extracts asistencia.csv: 25 participants, 22 completed', () => {
    const result = extractDocument(fixture('asistencia.csv'), 'text/csv')
    expect(result.status).toBe('extracted')
    const rows = result.tables[0].rows
    // banner + header + 25 participants
    expect(rows).toHaveLength(27)
    expect(rows[1]).toEqual([
      'participante_id',
      'rol',
      'talleres_asistidos',
      'talleres_totales',
      'completo_formacion',
    ])
    const dataRows = rows.slice(2)
    expect(dataRows).toHaveLength(25)
    expect(dataRows.filter((r) => r[4] === 'si')).toHaveLength(22)
    expect(dataRows.filter((r) => r[4] === 'no')).toHaveLength(25 - 22)
    // deterministic fixture snapshot: LID-23 dropped out
    expect(dataRows[22]).toEqual(['LID-23', 'Vocal', '6', '12', 'no'])
  })

  it('accepts a MIME type with parameters', () => {
    const result = extractDocument(fixture('asistencia.csv'), 'text/csv; charset=utf-8')
    expect(result.status).toBe('extracted')
    expect(result.tables[0].rows).toHaveLength(27)
  })
})

describe('extractDocument — RFC 4180 edge cases', () => {
  it('parses quoted fields with embedded commas, newlines and escaped quotes', () => {
    const csv = 'a,"b,c","line1\nline2","he said ""hi""",plain\r\nx,y,z,w,v\n'
    const result = extractDocument(Buffer.from(csv, 'utf8'), 'text/csv')
    expect(result.status).toBe('extracted')
    expect(result.tables[0].rows).toEqual([
      ['a', 'b,c', 'line1\nline2', 'he said "hi"', 'plain'],
      ['x', 'y', 'z', 'w', 'v'],
    ])
  })

  it('does not emit a phantom empty row for a trailing newline', () => {
    const result = extractDocument(Buffer.from('a,b\nc,d\n', 'utf8'), 'text/csv')
    expect(result.tables[0].rows).toEqual([
      ['a', 'b'],
      ['c', 'd'],
    ])
  })

  it('warns on an unterminated quoted field instead of throwing', () => {
    const result = extractDocument(Buffer.from('a,"unterminated\nb,c', 'utf8'), 'text/csv')
    expect(result.status).toBe('extracted')
    expect(result.warnings.some((w) => w.includes('unterminated'))).toBe(true)
  })
})

describe('extractDocument — text/plain (real fixture)', () => {
  it('extracts testimonios.txt verbatim with no pages or tables', () => {
    const buffer = fixture('testimonios.txt')
    const result = extractDocument(buffer, 'text/plain')
    expect(result.status).toBe('extracted')
    expect(result.text).toBe(buffer.toString('utf8'))
    expect(result.text).toContain('TESTIMONIO 1 — Hogar HOG-014')
    expect(result.text).toContain('el comité sigue')
    expect(result.pages).toEqual([])
    expect(result.tables).toEqual([])
    expect(result.meta.truncated).toBe(false)
  })

  it('strips a UTF-8 BOM', () => {
    const result = extractDocument(Buffer.from('﻿hola', 'utf8'), 'text/plain')
    expect(result.text).toBe('hola')
  })
})

describe('extractDocument — unsupported formats (G5 dependency decision)', () => {
  it('reports PDF fixtures as unsupported, naming the G5 gate', () => {
    for (const name of ['acta-entrega.pdf', 'informe-continuidad.pdf']) {
      const result = extractDocument(fixture(name), 'application/pdf')
      expect(result.status).toBe('unsupported')
      expect(result.text).toBe('')
      expect(result.pages).toEqual([])
      expect(result.tables).toEqual([])
      expect(result.warnings).toHaveLength(1)
      expect(result.warnings[0]).toMatch(/G5/)
      expect(result.warnings[0]).toMatch(/pdf/i)
    }
  })

  it('reports the XLSX fixture as unsupported, naming the G5 gate', () => {
    const result = extractDocument(
      fixture('inversiones.xlsx'),
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    )
    expect(result.status).toBe('unsupported')
    expect(result.warnings[0]).toMatch(/G5/)
    expect(result.warnings[0]).toMatch(/xlsx|spreadsheet/i)
  })

  it('reports unknown MIME types as unsupported without naming a gate dependency', () => {
    const result = extractDocument(Buffer.from('GIF89a'), 'image/gif')
    expect(result.status).toBe('unsupported')
    expect(result.warnings).toHaveLength(1)
  })
})

describe('extractDocument — caps', () => {
  it('mirrors the 25 MB evidence upload cap and errors above it', () => {
    expect(MAX_GROUNDING_INPUT_BYTES).toBe(25 * 1024 * 1024)
    const oversized = Buffer.alloc(MAX_GROUNDING_INPUT_BYTES + 1)
    const result = extractDocument(oversized, 'text/plain')
    expect(result.status).toBe('error')
    expect(result.text).toBe('')
    expect(result.warnings[0]).toMatch(/25/)
  })

  it('truncates extracted text above the char cap and flags it', () => {
    const big = 'linea de texto repetida para superar el tope\n'.repeat(
      Math.ceil((MAX_EXTRACTED_TEXT_CHARS + 10_000) / 45),
    )
    const result = extractDocument(Buffer.from(big, 'utf8'), 'text/plain')
    expect(result.status).toBe('extracted')
    expect(result.meta.truncated).toBe(true)
    expect(result.text).toHaveLength(MAX_EXTRACTED_TEXT_CHARS)
    expect(result.warnings.some((w) => w.includes('truncated'))).toBe(true)
  })
})
