#!/usr/bin/env bash
# scripts/capability-dry-run.sh
#
# The capability campaign's dry run, end to end, in a DISPOSABLE container.
#
# WHAT IT PROVES
#   baseline 38 tables / 107 policies  ->  apply 0006..0010 twice  ->  42 / 141
#   -> 67 live assertions (13+12+14+13+15) + cross-isolation + concurrency = 72
#   -> roll back all five  ->  0 capability roles, 0 cap_* policies, 0 functions,
#      schema gone, exactly two tables retained
#   -> re-apply  ->  identical state.
#
# WHAT IT NEVER TOUCHES
#   The live stack is read ONCE, read-only, to produce a schema-only dump and a
#   password-free role list. Everything after that happens inside a container
#   started with --network none, which is destroyed at the end. No remote.
#
# THE SEEDING DETAIL THAT MATTERS. `pg_dump --schema-only` does not carry the
# ACL of schema `public` when the schema is created by hand at restore time, and
# the difference is not cosmetic: the live stack has `=U/pg_database_owner` —
# PUBLIC holds USAGE, which is RR-CAP-7 — and every capability role inherits it.
# Without that grant the definers cannot even name `public.users`, every
# capability call fails 42501, and the run measures the seeding rather than the
# packages. The ACL is restored explicitly below.
#
#   bash scripts/capability-dry-run.sh
#
# DO NOT EDIT THIS FILE WHILE IT IS RUNNING. bash reads a script incrementally,
# by byte offset, so changing its length mid-run makes the interpreter resume at
# the wrong place. Observed: an edit to a comment during step 3 produced
# «concurrency.sh: command not found» at step 5 and a run that stopped silently
# after reporting success on everything before it.
#
set -euo pipefail
export MSYS_NO_PATHCONV=1

LIVE_CONTAINER="${LIVE_CONTAINER:-supabase_db_uellix-stella-g2-local-rehearsal}"
IMAGE="${IMAGE:-public.ecr.aws/supabase/postgres:17.6.1.143}"
BOX="uellix_cap_dryrun"
WORK="$(mktemp -d)"
PSQL=(docker exec "$BOX" psql -U supabase_admin -d postgres)
PACKAGES=(0006_invitation_capability 0007_public_verification_capability
          0008_stripe_webhook_identity 0009_public_lead_capability
          0010_organization_bootstrap_capability)
ROLLBACKS=(0010_rollback 0009_rollback 0008_rollback 0007_rollback 0006_rollback)

cleanup() { docker rm -f "$BOX" >/dev/null 2>&1 || true; rm -rf "$WORK"; }
trap cleanup EXIT

# MSYS_NO_PATHCONV stops Git Bash rewriting the CONTAINER side of a docker cp,
# which is required — but it also stops it rewriting the HOST side, and Docker
# for Windows then reads `/tmp/x` as `C:\tmp\x`. Convert host paths explicitly.
hp() { if command -v cygpath >/dev/null 2>&1; then cygpath -w "$1"; else printf '%s' "$1"; fi; }

say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }
state() { "${PSQL[@]}" -tAc "
  SELECT (SELECT count(*) FROM pg_tables  WHERE schemaname='public') || '/' ||
         (SELECT count(*) FROM pg_policies WHERE schemaname='public') || '/' ||
         (SELECT count(*) FROM pg_roles WHERE rolname LIKE 'uellix_cap%' OR rolname='uellix_stripe') || '/' ||
         (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='uellix_capability') || '/' ||
         (SELECT count(*) FROM pg_namespace WHERE nspname='uellix_capability')"; }

# --------------------------------------------------------------------------
say "0. Read the live stack, read-only"
# --------------------------------------------------------------------------
docker exec "$LIVE_CONTAINER" pg_dumpall -U postgres --roles-only --no-role-passwords > "$WORK/roles.sql"
docker exec "$LIVE_CONTAINER" pg_dump    -U postgres -d postgres --schema-only        > "$WORK/schema.sql"
LIVE_STATE=$(docker exec "$LIVE_CONTAINER" psql -U postgres -tAc "
  SELECT (SELECT count(*) FROM pg_tables WHERE schemaname='public') || '/' ||
         (SELECT count(*) FROM pg_policies WHERE schemaname='public')")
echo "live baseline: $LIVE_STATE  (tables/policies)"
[ "$LIVE_STATE" = "38/107" ] || { echo "FATAL: live baseline is not 38/107"; exit 1; }

# --------------------------------------------------------------------------
say "1. Disposable container, no network"
# --------------------------------------------------------------------------
docker rm -f "$BOX" >/dev/null 2>&1 || true
docker run -d --name "$BOX" --network none \
  -e POSTGRES_PASSWORD=dryrun -e POSTGRES_HOST_AUTH_METHOD=trust "$IMAGE" >/dev/null
# pg_isready is not enough: the image's entrypoint runs initdb against a
# TEMPORARY server on the same socket and then shuts it down, so a probe can
# succeed against a server that is about to disappear. Requiring N consecutive
# successful real queries waits for the second, permanent start.
ok=0
for _ in $(seq 1 90); do
  if "${PSQL[@]}" -tAc "SELECT 1" >/dev/null 2>&1; then ok=$((ok + 1)); else ok=0; fi
  [ "$ok" -ge 3 ] && break
  sleep 2
done
[ "$ok" -ge 3 ] || { echo "FATAL: the disposable server never came up"; docker logs --tail 20 "$BOX"; exit 1; }
"${PSQL[@]}" -tAc "SELECT version()" | head -1

# --------------------------------------------------------------------------
say "2. Seed from the dump"
# --------------------------------------------------------------------------
docker cp "$(hp "$WORK/roles.sql")"  "$BOX:/roles.sql"
docker cp "$(hp "$WORK/schema.sql")" "$BOX:/schema.sql"
# The reserved-role errors are expected: anon, authenticated and friends already
# exist in the image, and ALTER on them needs a superuser the dump does not run as.
"${PSQL[@]}" -q -f /roles.sql >/dev/null 2>&1 || true
"${PSQL[@]}" -q -c "CREATE SCHEMA IF NOT EXISTS public AUTHORIZATION pg_database_owner" >/dev/null
"${PSQL[@]}" -q -f /schema.sql >/dev/null 2>&1 || true
# See the header: this is what makes the run measure the packages.
"${PSQL[@]}" -q -c "ALTER SCHEMA public OWNER TO pg_database_owner; GRANT USAGE ON SCHEMA public TO PUBLIC;" >/dev/null

BASE=$(state); echo "container baseline: $BASE  (tables/policies/roles/functions/schema)"
[ "${BASE%%/*}" = "38" ] || { echo "FATAL: seeded table count is not 38"; exit 1; }
[ "$(echo "$BASE" | cut -d/ -f2)" = "107" ] || { echo "FATAL: seeded policy count is not 107"; exit 1; }

for f in "${PACKAGES[@]}" "${ROLLBACKS[@]}"; do
  docker cp "db/prepared/stella_$f.sql" "$BOX:/prepared_stella_$f.sql"
done
docker cp scripts/capability-dry-run.sql "$BOX:/dryrun.sql"

# --------------------------------------------------------------------------
say "3. Apply 0006..0010, twice"
# --------------------------------------------------------------------------
for pass in 1 2; do
  for f in "${PACKAGES[@]}"; do
    printf '  pass %s  stella_%-46s ' "$pass" "$f"
    if "${PSQL[@]}" -1 -v ON_ERROR_STOP=1 -q -f "/prepared_stella_$f.sql" >/dev/null 2>"$WORK/err"; then
      echo "OK"
    else
      echo "FAIL"; cat "$WORK/err"; exit 1
    fi
  done
  echo "  state after pass $pass: $(state)"
done
AFTER=$(state)
[ "$AFTER" = "42/141/6/8/1" ] || { echo "FATAL: expected 42/141/6/8/1, got $AFTER"; exit 1; }

# --------------------------------------------------------------------------
say "4. The 67 live assertions, cross-isolation and concurrency"
# --------------------------------------------------------------------------
"${PSQL[@]}" -q -c "CREATE SCHEMA IF NOT EXISTS dryrun; CREATE TABLE IF NOT EXISTS dryrun.disposable_marker(x int);" >/dev/null
"${PSQL[@]}" -v ON_ERROR_STOP=1 -f /dryrun.sql 2>&1 | tail -n +2 | grep -Ev '^(DO|CREATE|TRUNCATE|NOTICE)' || true
bash scripts/capability-dry-run-concurrency.sh "$BOX"
"${PSQL[@]}" -tAc "SELECT 'live assertions: ' || count(*) FILTER (WHERE ok) || ' passed, ' || count(*) FILTER (WHERE NOT ok) || ' failed' FROM dryrun.results"
FAILED=$("${PSQL[@]}" -tAc "SELECT count(*) FROM dryrun.results WHERE NOT ok")
if [ "$FAILED" != "0" ]; then
  "${PSQL[@]}" -c "SELECT id, detail FROM dryrun.results WHERE NOT ok ORDER BY id"
  echo "FATAL: $FAILED live assertions failed"; exit 1
fi

# --------------------------------------------------------------------------
say "5. Roll back all five, in reverse order"
# --------------------------------------------------------------------------
for f in "${ROLLBACKS[@]}"; do
  printf '  stella_%-20s ' "$f"
  if "${PSQL[@]}" -1 -v ON_ERROR_STOP=1 -q -f "/prepared_stella_$f.sql" >/dev/null 2>"$WORK/err"; then
    echo "OK"
  else
    echo "FAIL"; cat "$WORK/err"; exit 1
  fi
done

say "6. Teardown is complete"
"${PSQL[@]}" -c "
SELECT 'capability roles'      AS what, count(*) AS n FROM pg_roles WHERE rolname LIKE 'uellix_cap%' OR rolname = 'uellix_stripe'
UNION ALL SELECT 'cap_* policies',      count(*) FROM pg_policies WHERE policyname LIKE 'cap\\_%'
UNION ALL SELECT 'disclosures_ policies', count(*) FROM pg_policies WHERE policyname LIKE 'disclosures\\_%'
UNION ALL SELECT 'capability functions', count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'uellix_capability'
UNION ALL SELECT 'uellix_capability schema', count(*) FROM pg_namespace WHERE nspname = 'uellix_capability'
UNION ALL SELECT 'retained: report_public_disclosures', count(*) FROM pg_tables WHERE schemaname='public' AND tablename='report_public_disclosures'
UNION ALL SELECT 'retained: stripe_webhook_events',     count(*) FROM pg_tables WHERE schemaname='public' AND tablename='stripe_webhook_events'
UNION ALL SELECT 'dropped: capability_verification_hits',  count(*) FROM pg_tables WHERE schemaname='public' AND tablename='capability_verification_hits'
UNION ALL SELECT 'dropped: capability_bootstrap_attempts', count(*) FROM pg_tables WHERE schemaname='public' AND tablename='capability_bootstrap_attempts'
UNION ALL SELECT 'tables', count(*) FROM pg_tables WHERE schemaname='public'
UNION ALL SELECT 'policies', count(*) FROM pg_policies WHERE schemaname='public';"

# --------------------------------------------------------------------------
say "7. Re-apply — the state must be identical to step 3"
# --------------------------------------------------------------------------
for f in "${PACKAGES[@]}"; do
  printf '  stella_%-46s ' "$f"
  if "${PSQL[@]}" -1 -v ON_ERROR_STOP=1 -q -f "/prepared_stella_$f.sql" >/dev/null 2>"$WORK/err"; then
    echo "OK"
  else
    echo "FAIL"; cat "$WORK/err"; exit 1
  fi
done
REAPPLIED=$(state)
echo "  after re-apply: $REAPPLIED   (was $AFTER)"
[ "$REAPPLIED" = "$AFTER" ] || { echo "FATAL: re-apply did not converge"; exit 1; }

say "DRY RUN COMPLETE — container destroyed on exit"
