#!/usr/bin/env bash
# scripts/capability-dry-run.sh
#
# The capability campaign's dry run, end to end, in a DISPOSABLE container.
#
# WHAT IT PROVES
#   baseline 38 tables / 107 policies / 10 triggers
#     -> apply 0006..0010 twice -> 42 tables / 141 policies / 6 roles / 8 functions
#     -> 72 live assertions (single-session + cross-isolation + 6 contended)
#     -> roll back all five -> 40 tables / 108 policies, 0 capability roles,
#        0 cap_* policies, 0 functions, schema gone, exactly two tables and
#        exactly one policy retained
#     -> re-apply -> identical state.
#
# EVERY ONE OF THOSE NUMBERS IS AN ASSERTION, NOT A PRINTOUT.
#
# Until this revision the run reported the teardown as a nine-row table and
# moved on, and step 4 ended with `| grep -Ev '…' || true`. The combination has
# a specific failure mode: psql exiting non-zero was discarded by the pipe and
# then by the `|| true`, and the only completeness check afterwards asked how
# many recorded assertions had FAILED. A run that died after thirty assertions
# had thirty rows, none of them failing, and reported success. Absence of
# failure is not evidence of completion, so the assertion COUNT is now checked
# against $EXPECTED_ASSERTIONS and the concurrency subset against
# $EXPECTED_CONCURRENCY.
#
# WHAT IT NEVER TOUCHES
#   Nothing outside its own disposable container. There is no live stack in the
#   loop: the baseline comes from the VERSIONED artifacts under db/baseline/,
#   whose hashes are checked before anything starts. No persistent volume is
#   mounted, no port is published, the container runs with --network none and is
#   destroyed on exit. No remote.
#
#   Until 2026-08-04 this script began by running `pg_dumpall --roles-only` and
#   `pg_dump --schema-only` against the container
#   `supabase_db_uellix-stella-g2-local-rehearsal`. That made the whole rehearsal
#   unreproducible: the "baseline" was a side effect of a `mktemp -d` that the
#   exit trap deleted, it was never committed, never hashed, and it only existed
#   while that one container happened to be alive. See db/baseline/README.md.
#
# THE SEEDING DETAIL THAT MATTERS. `pg_dump --schema-only` does not emit the
# ACL entry of schema `public` that corresponds to PUBLIC, and the difference is
# not cosmetic: the baseline has `=U/pg_database_owner` — PUBLIC holds USAGE,
# which is RR-CAP-7 — and every capability role inherits it. Without that grant
# the definers cannot even name `public.users`, every capability call fails
# 42501, and the run measures the seeding rather than the packages. That grant
# used to be patched in by hand, unversioned, right here; it now lives in
# db/baseline/stella_g2_post_restore.sql, hashed in the manifest and asserted by
# tests/capability-baseline-artifact.test.ts.
#
#   bash scripts/capability-dry-run.sh
#
# DO NOT EDIT THIS FILE WHILE IT IS RUNNING. bash reads a script incrementally,
# by byte offset, so changing its length mid-run makes the interpreter resume at
# the wrong place. Observed: an edit to a comment during step 3 produced
# «concurrency.sh: command not found» at step 5 and a run that stopped silently
# after reporting success on everything before it.
#
set -euo pipefail
export MSYS_NO_PATHCONV=1

IMAGE="${IMAGE:-public.ecr.aws/supabase/postgres:17.6.1.143}"
BASE_DIR="db/baseline"
BOX="uellix_cap_dryrun"
WORK="$(mktemp -d)"
PSQL=(docker exec "$BOX" psql -U supabase_admin -d postgres)
# 0011 is applied LAST and rolled back FIRST. It is not a capability in the
# CAP-01..CAP-05 sense — it narrows an existing ACL — but it creates a definer
# in the shared uellix_capability schema, and every other rollback drops that
# schema once it is empty. Rolling 0011 back after the five would find the
# schema already gone.
# 0012 closes the self-escalation that made 0011's boundary decorative: the
# quota was moved behind current_user_is_super_admin(), and the runtime could
# write the single column that predicate reads. It creates NOTHING — two column
# ACLs — so the state tuple below is unchanged by it.
PACKAGES=(0006_invitation_capability 0007_public_verification_capability
          0008_stripe_webhook_identity 0009_public_lead_capability
          0010_organization_bootstrap_capability 0011_organization_column_acl
          0012_super_admin_column_acl)
ROLLBACKS=(0012_rollback 0011_rollback 0010_rollback 0009_rollback 0008_rollback
           0007_rollback 0006_rollback)

# Every number this run must reproduce, in one place, so a change to any of
# them is a visible edit rather than a drifting expectation.
EXPECTED_BASELINE="38/107/0/0/0"     # tables/policies/cap roles/cap functions/cap schema
EXPECTED_BASELINE_TRIGGERS=10
EXPECTED_FORWARD="42/151/7/10/1"
EXPECTED_ASSERTIONS=132
EXPECTED_CONCURRENCY=7
EXPECTED_ROLLBACK_TABLES=40
EXPECTED_ROLLBACK_POLICIES=108
EXPECTED_RETAINED_TABLES=2
EXPECTED_RETAINED_POLICIES=1

cleanup() { docker rm -f "$BOX" >/dev/null 2>&1 || true; rm -rf "$WORK"; }
trap cleanup EXIT

# MSYS_NO_PATHCONV stops Git Bash rewriting the CONTAINER side of a docker cp,
# which is required — but it also stops it rewriting the HOST side, and Docker
# for Windows then reads `/tmp/x` as `C:\tmp\x`. Convert host paths explicitly.
hp() { if command -v cygpath >/dev/null 2>&1; then cygpath -w "$1"; else printf '%s' "$1"; fi; }

say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }
state() { "${PSQL[@]}" -tAc "
  SELECT (SELECT count(*) FROM pg_tables  WHERE schemaname='public') || '/' ||
         (SELECT count(*) FROM pg_policies WHERE schemaname='public') || '/' ||
         (SELECT count(*) FROM pg_roles WHERE rolname LIKE 'uellix_cap%' OR rolname='uellix_stripe') || '/' ||
         (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='uellix_capability') || '/' ||
         (SELECT count(*) FROM pg_namespace WHERE nspname='uellix_capability')"; }

# --------------------------------------------------------------------------
say "0. Verify the versioned baseline artifacts"
# --------------------------------------------------------------------------
[ -f "$BASE_DIR/MANIFEST.sha256" ] || { echo "FATAL: missing $BASE_DIR/MANIFEST.sha256"; exit 1; }
( cd "$BASE_DIR" && sha256sum -c MANIFEST.sha256 ) \
  || { echo "FATAL: baseline artifacts do not match the manifest"; exit 1; }

# --------------------------------------------------------------------------
say "1. Disposable container, no network"
# --------------------------------------------------------------------------
docker rm -f "$BOX" >/dev/null 2>&1 || true
# `-D /etc/postgresql` is the image's own Cmd and carries shared_preload_libraries;
# passing arguments replaces the Cmd wholesale, so dropping it would leave pg_net
# unloaded and the restore would die on `CREATE EXTENSION pg_net`.
# The two `database_name` overrides matter because step 2 recreates the
# `postgres` database: the pg_cron launcher exits 1 when its database vanishes
# and the pg_net worker SEGFAULTS, and either death makes the postmaster
# reinitialise the whole cluster mid-restore.
docker run -d --name "$BOX" --network none \
  -e POSTGRES_PASSWORD=dryrun -e POSTGRES_HOST_AUTH_METHOD=trust \
  "$IMAGE" postgres -D /etc/postgresql \
    -c cron.database_name=template1 -c pg_net.database_name=template1 >/dev/null
# pg_isready is not enough: the image's entrypoint runs initdb against a
# TEMPORARY server on the same socket and then shuts it down, so a probe can
# succeed against a server that is about to disappear. Requiring N consecutive
# successful real queries waits for the second, permanent start.
ok=0
for _ in $(seq 1 90); do
  if "${PSQL[@]}" -tAc "SELECT 1" >/dev/null 2>&1; then ok=$((ok + 1)); else ok=0; fi
  [ "$ok" -ge 3 ] && break
  sleep 2
done
[ "$ok" -ge 3 ] || { echo "FATAL: the disposable server never came up"; docker logs --tail 20 "$BOX"; exit 1; }
"${PSQL[@]}" -tAc "SELECT version()" | head -1
# The server version is part of what the run proves. A different major would
# change RLS, ownership and privilege semantics under the same SQL, and the
# report would attribute the result to the packages.
PGVER="$("${PSQL[@]}" -tAc "SHOW server_version")"
case "$PGVER" in
  17.6*) echo "  server_version: $PGVER" ;;
  *) echo "FATAL: server_version is $PGVER, expected 17.6"; exit 1 ;;
esac
echo "  image: $IMAGE"
docker image inspect "$IMAGE" --format '  image id: {{.Id}}' || true

# --------------------------------------------------------------------------
say "2. Restore the baseline, fail-closed"
# --------------------------------------------------------------------------
# The image ships its own `postgres` database, already populated with auth,
# storage, realtime, graphql and vault. Restoring the dump on top of it collides
# on every CREATE SCHEMA — which is precisely what the previous `|| true` hid.
# Recreating the database from template0 gives the dump an empty target, so the
# restore runs with ON_ERROR_STOP=1 and no error is swallowed anywhere.
docker exec "$BOX" psql -U supabase_admin -d template1 -v ON_ERROR_STOP=1 -q -c \
  "UPDATE pg_database SET datallowconn = false WHERE datname = 'postgres'" >/dev/null
dropped=0
for _ in $(seq 1 15); do
  docker exec "$BOX" psql -U supabase_admin -d template1 -q -c \
    "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'postgres' AND pid <> pg_backend_pid()" >/dev/null 2>&1 || true
  if docker exec "$BOX" psql -U supabase_admin -d template1 -v ON_ERROR_STOP=1 -q -c \
       "DROP DATABASE IF EXISTS postgres" >/dev/null 2>&1; then dropped=1; break; fi
  sleep 1
done
[ "$dropped" = "1" ] || { echo "FATAL: could not drop the factory postgres database"; exit 1; }
docker exec "$BOX" psql -U supabase_admin -d template1 -v ON_ERROR_STOP=1 -q -c \
  "CREATE DATABASE postgres TEMPLATE template0 OWNER postgres" >/dev/null \
  || { echo "FATAL: could not recreate the postgres database"; exit 1; }

for f in stella_g2_roles.sql stella_g2_schema.sql stella_g2_post_restore.sql; do
  docker cp "$(hp "$BASE_DIR/$f")" "$BOX:/$f"
done
# No `|| true` on any of the three. The NOTICEs about memberships that already
# exist are not errors and do not abort under ON_ERROR_STOP=1.
"${PSQL[@]}" -v ON_ERROR_STOP=1 -q -f /stella_g2_roles.sql        >/dev/null || { echo "FATAL: roles restore failed";  exit 1; }
"${PSQL[@]}" -v ON_ERROR_STOP=1 -q -f /stella_g2_schema.sql       >/dev/null || { echo "FATAL: schema restore failed"; exit 1; }
"${PSQL[@]}" -v ON_ERROR_STOP=1 -q -f /stella_g2_post_restore.sql >/dev/null || { echo "FATAL: post-restore failed";   exit 1; }

BASE=$(state); echo "container baseline: $BASE  (tables/policies/roles/functions/schema)"
# HARD, not advisory. The baseline is the denominator of every number this run
# reports: 42 tables means nothing without 38 before it. A partially restored
# baseline would make the packages look like they created more than they do.
[ "$BASE" = "$EXPECTED_BASELINE" ] \
  || { echo "FATAL: baseline is $BASE, expected $EXPECTED_BASELINE (tables/policies/cap roles/cap functions/cap schema)"; exit 1; }
BASE_TRIGGERS=$("${PSQL[@]}" -tAc "
  SELECT count(*) FROM pg_trigger t
    JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND NOT t.tgisinternal")
[ "$BASE_TRIGGERS" = "$EXPECTED_BASELINE_TRIGGERS" ] \
  || { echo "FATAL: baseline trigger count is $BASE_TRIGGERS, expected $EXPECTED_BASELINE_TRIGGERS"; exit 1; }
BASE_CAP_POL=$("${PSQL[@]}" -tAc "SELECT count(*) FROM pg_policies WHERE policyname LIKE 'cap\\_%'")
[ "$BASE_CAP_POL" = "0" ] || { echo "FATAL: the baseline already carries $BASE_CAP_POL cap_* policies"; exit 1; }
echo "  baseline asserted: 38 tables / 107 policies / 10 triggers / 0 capability objects"

for f in "${PACKAGES[@]}" "${ROLLBACKS[@]}"; do
  docker cp "db/prepared/stella_$f.sql" "$BOX:/prepared_stella_$f.sql"
done
docker cp scripts/capability-dry-run.sql "$BOX:/dryrun.sql"

# --------------------------------------------------------------------------
say "3. Apply 0006..0010, twice"
# --------------------------------------------------------------------------
PASS1_STATE=""
for pass in 1 2; do
  for f in "${PACKAGES[@]}"; do
    printf '  pass %s  stella_%-46s ' "$pass" "$f"
    if "${PSQL[@]}" -1 -v ON_ERROR_STOP=1 -q -f "/prepared_stella_$f.sql" >/dev/null 2>"$WORK/err"; then
      echo "OK"
    else
      echo "FAIL"; cat "$WORK/err"; exit 1
    fi
  done
  PASS_STATE=$(state)
  echo "  state after pass $pass: $PASS_STATE"
  # `[ … ] && X` would be the loop body's LAST command, and a false test then
  # makes the body exit non-zero — which `set -e` treats as a failed run.
  if [ "$pass" = "1" ]; then PASS1_STATE="$PASS_STATE"; fi
done
AFTER=$(state)
[ "$AFTER" = "$EXPECTED_FORWARD" ] || { echo "FATAL: expected $EXPECTED_FORWARD, got $AFTER"; exit 1; }
# Convergence is the property that makes a second apply safe. Asserting the two
# passes produce the same state is what "idempotent" means here; a duplicate
# policy or a second role would show up as a different tuple.
[ "$PASS1_STATE" = "$AFTER" ] \
  || { echo "FATAL: pass 1 left $PASS1_STATE and pass 2 left $AFTER — the packages are not convergent"; exit 1; }
DUP_POLICIES=$("${PSQL[@]}" -tAc "
  SELECT count(*) FROM (
    SELECT schemaname, tablename, policyname FROM pg_policies WHERE schemaname='public'
    GROUP BY 1,2,3 HAVING count(*) > 1) d")
[ "$DUP_POLICIES" = "0" ] || { echo "FATAL: $DUP_POLICIES duplicated policies after two passes"; exit 1; }

# --------------------------------------------------------------------------
# 72, and the split that matters to whoever edits $EXPECTED_ASSERTIONS is the
# one BY SOURCE, not by document. capability-dry-run.sql records 66 rows (63
# `L*` cases plus three cross-isolation ones); the concurrency script records 6
# (four `L*` cases that need two real sessions, plus CAP-02 and CAP-04 under
# contention). 66 + 6 = 72. The design's own count of 67 `L*` cases is spread
# across both files, which is why a naive count of the .sql gives 66 and looks
# like a contradiction.
say "4. The 132 live assertions (125 from dryrun.sql + 7 concurrency assertions)"
# --------------------------------------------------------------------------
"${PSQL[@]}" -q -c "CREATE SCHEMA IF NOT EXISTS dryrun; CREATE TABLE IF NOT EXISTS dryrun.disposable_marker(x int);" >/dev/null

# THE EXIT CODE OF dryrun.sql IS THE POINT, AND IT USED TO BE THROWN AWAY.
#
# The previous line ended `| tail -n +2 | grep -Ev '…' || true`. Two separate
# losses, and they compound:
#
#   * the pipe hands the pipeline's status to grep, and `|| true` then discards
#     even that, so psql exiting 3 on ON_ERROR_STOP was indistinguishable from
#     psql exiting 0;
#   * the only completeness check afterwards was "how many rows say NOT ok",
#     and a run that DIED after thirty assertions has thirty rows, none of them
#     failing. A partial execution reported as green.
#
# So: the output goes to a file, the real status is captured, the file is
# scanned for ERROR, and the row COUNT is asserted against the expected total.
# Absence of failure is not evidence of completion.
set +e
"${PSQL[@]}" -v ON_ERROR_STOP=1 -f /dryrun.sql >"$WORK/dryrun.out" 2>&1
DRY_RC=$?
set -e
# Display only. grep exits 1 when nothing matches, which is not a failure of
# anything — the run's status was captured above and is checked below.
grep -Ev '^(DO|CREATE|TRUNCATE|NOTICE)' "$WORK/dryrun.out" | tail -n +2 || true
if [ "$DRY_RC" != "0" ]; then
  echo "FATAL: dryrun.sql exited $DRY_RC"; tail -n 40 "$WORK/dryrun.out"; exit 1
fi
if grep -qE '(^|:)ERROR:' "$WORK/dryrun.out"; then
  echo "FATAL: dryrun.sql reported an ERROR"; grep -nE '(^|:)ERROR:' "$WORK/dryrun.out" | head -n 20; exit 1
fi

bash scripts/capability-dry-run-concurrency.sh "$BOX"

# The six contended cases are recorded by the concurrency script under ids the
# single-session harness cannot produce. Counting them separately is what makes
# "6/6" a measurement rather than a restatement of the total.
CONC_IDS="'CAP01-L6','CAP02-CONC','CAP03-L3','CAP04-CONC','CAP05-L4','CAP05-L11','CAP03-LOCK'"
read -r TOTAL PASSED FAILED CONC_TOTAL CONC_PASSED <<<"$("${PSQL[@]}" -tAc "
  SELECT count(*) || ' ' ||
         count(*) FILTER (WHERE ok) || ' ' ||
         count(*) FILTER (WHERE NOT ok) || ' ' ||
         count(*) FILTER (WHERE id IN ($CONC_IDS)) || ' ' ||
         count(*) FILTER (WHERE id IN ($CONC_IDS) AND ok)
    FROM dryrun.results")"
echo "live assertions: $PASSED passed, $FAILED failed, $TOTAL executed (concurrency $CONC_PASSED/$CONC_TOTAL)"
if [ "$FAILED" != "0" ]; then
  "${PSQL[@]}" -c "SELECT id, detail FROM dryrun.results WHERE NOT ok ORDER BY id"
  echo "FATAL: $FAILED live assertions failed"; exit 1
fi
[ "$TOTAL" = "$EXPECTED_ASSERTIONS" ] \
  || { echo "FATAL: $TOTAL assertions executed, expected $EXPECTED_ASSERTIONS — the run is PARTIAL, not green"; exit 1; }
[ "$PASSED" = "$EXPECTED_ASSERTIONS" ] \
  || { echo "FATAL: $PASSED assertions passed, expected $EXPECTED_ASSERTIONS"; exit 1; }
[ "$CONC_TOTAL" = "$EXPECTED_CONCURRENCY" ] \
  || { echo "FATAL: $CONC_TOTAL concurrency assertions executed, expected $EXPECTED_CONCURRENCY"; exit 1; }
[ "$CONC_PASSED" = "$EXPECTED_CONCURRENCY" ] \
  || { echo "FATAL: $CONC_PASSED concurrency assertions passed, expected $EXPECTED_CONCURRENCY"; exit 1; }

# --------------------------------------------------------------------------
say "5. Roll back all five, in reverse order"
# --------------------------------------------------------------------------
for f in "${ROLLBACKS[@]}"; do
  printf '  stella_%-20s ' "$f"
  if "${PSQL[@]}" -1 -v ON_ERROR_STOP=1 -q -f "/prepared_stella_$f.sql" >/dev/null 2>"$WORK/err"; then
    echo "OK"
  else
    echo "FAIL"; cat "$WORK/err"; exit 1
  fi
done

say "6. Teardown is complete"
"${PSQL[@]}" -c "
SELECT 'capability roles'      AS what, count(*) AS n FROM pg_roles WHERE rolname LIKE 'uellix_cap%' OR rolname = 'uellix_stripe'
UNION ALL SELECT 'cap_* policies',      count(*) FROM pg_policies WHERE policyname LIKE 'cap\\_%'
UNION ALL SELECT 'disclosures_ policies', count(*) FROM pg_policies WHERE policyname LIKE 'disclosures\\_%'
UNION ALL SELECT 'capability functions', count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'uellix_capability'
UNION ALL SELECT 'uellix_capability schema', count(*) FROM pg_namespace WHERE nspname = 'uellix_capability'
UNION ALL SELECT 'retained: report_public_disclosures', count(*) FROM pg_tables WHERE schemaname='public' AND tablename='report_public_disclosures'
UNION ALL SELECT 'retained: stripe_webhook_events',     count(*) FROM pg_tables WHERE schemaname='public' AND tablename='stripe_webhook_events'
UNION ALL SELECT 'dropped: capability_verification_hits',  count(*) FROM pg_tables WHERE schemaname='public' AND tablename='capability_verification_hits'
UNION ALL SELECT 'dropped: capability_bootstrap_attempts', count(*) FROM pg_tables WHERE schemaname='public' AND tablename='capability_bootstrap_attempts'
UNION ALL SELECT 'tables', count(*) FROM pg_tables WHERE schemaname='public'
UNION ALL SELECT 'policies', count(*) FROM pg_policies WHERE schemaname='public';"

# The table above is a REPORT. What follows are the assertions, and the
# difference matters: printing nine numbers proves nothing unless something
# refuses when one of them is wrong. Until now the teardown step printed and
# moved on, so a rollback that left a capability role behind produced a run
# that ended «DRY RUN COMPLETE».
read -r RB_TABLES RB_POLICIES RB_CAPROLES RB_CAPFN RB_SCHEMA RB_CAPPOL RB_DISC RB_RETAINED RB_DROPPED <<<"$("${PSQL[@]}" -tAc "
  SELECT (SELECT count(*) FROM pg_tables   WHERE schemaname='public') || ' ' ||
         (SELECT count(*) FROM pg_policies WHERE schemaname='public') || ' ' ||
         (SELECT count(*) FROM pg_roles WHERE rolname LIKE 'uellix_cap%' OR rolname='uellix_stripe') || ' ' ||
         (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='uellix_capability') || ' ' ||
         (SELECT count(*) FROM pg_namespace WHERE nspname='uellix_capability') || ' ' ||
         (SELECT count(*) FROM pg_policies WHERE policyname LIKE 'cap\\_%') || ' ' ||
         (SELECT count(*) FROM pg_policies WHERE policyname LIKE 'disclosures\\_%') || ' ' ||
         (SELECT count(*) FROM pg_tables WHERE schemaname='public'
            AND tablename IN ('report_public_disclosures','stripe_webhook_events')) || ' ' ||
         (SELECT count(*) FROM pg_tables WHERE schemaname='public'
            AND tablename IN ('capability_verification_hits','capability_bootstrap_attempts'))")"

rb_assert() { # name actual expected
  if [ "$2" != "$3" ]; then echo "FATAL: after rollback, $1 is $2, expected $3"; exit 1; fi
}
rb_assert "public tables"                "$RB_TABLES"    "$EXPECTED_ROLLBACK_TABLES"
rb_assert "public policies"              "$RB_POLICIES"  "$EXPECTED_ROLLBACK_POLICIES"
rb_assert "capability roles"             "$RB_CAPROLES"  "0"
rb_assert "capability functions"         "$RB_CAPFN"     "0"
rb_assert "uellix_capability schema"     "$RB_SCHEMA"    "0"
rb_assert "cap_* policies"               "$RB_CAPPOL"    "0"
# Exactly ONE policy survives the campaign: CAP-02 retains
# disclosures_select_member so an organisation admin can still read what was
# published. "At least one" would be satisfied by the two the rollback was
# supposed to drop.
rb_assert "retained disclosures_ policies" "$RB_DISC"    "$EXPECTED_RETAINED_POLICIES"
rb_assert "retained tables"              "$RB_RETAINED"  "$EXPECTED_RETAINED_TABLES"
rb_assert "capability tables still present" "$RB_DROPPED" "0"
echo "  rollback asserted: $RB_TABLES tables / $RB_POLICIES policies / 2 retained tables / 1 retained policy"

# --------------------------------------------------------------------------
say "7. Re-apply — the state must be identical to step 3"
# --------------------------------------------------------------------------
for f in "${PACKAGES[@]}"; do
  printf '  stella_%-46s ' "$f"
  if "${PSQL[@]}" -1 -v ON_ERROR_STOP=1 -q -f "/prepared_stella_$f.sql" >/dev/null 2>"$WORK/err"; then
    echo "OK"
  else
    echo "FAIL"; cat "$WORK/err"; exit 1
  fi
done
REAPPLIED=$(state)
echo "  after re-apply: $REAPPLIED   (was $AFTER)"
[ "$REAPPLIED" = "$AFTER" ] || { echo "FATAL: re-apply did not converge"; exit 1; }
# Compared against the LITERAL too, not only against $AFTER. If the first apply
# had been wrong in the same way, comparing the two would agree and prove
# nothing.
[ "$REAPPLIED" = "$EXPECTED_FORWARD" ] \
  || { echo "FATAL: re-apply produced $REAPPLIED, expected $EXPECTED_FORWARD"; exit 1; }

say "DRY RUN COMPLETE — container destroyed on exit"
echo "  image            : $IMAGE"
echo "  server_version   : $PGVER"
echo "  baseline         : $BASE + $BASE_TRIGGERS triggers"
echo "  forward          : $AFTER"
echo "  live assertions  : $PASSED/$TOTAL (concurrency $CONC_PASSED/$CONC_TOTAL)"
echo "  rollback         : $RB_TABLES tables / $RB_POLICIES policies"
echo "  re-apply         : $REAPPLIED"
