// scripts/journal-artifacts.ts
// TRAIN 5C2 — generate or verify the 51 journal wrappers.
//
//   pnpm journal:generate   writes db/prepared/journal/*.sql
//   pnpm journal:verify     regenerates in memory and compares, byte for byte
//
// CONNECTS TO NOTHING. Reads the corpus, writes wrappers, exits.
//
// The wrappers are checked in for the same reason the storage artefacts are: the
// operator runs them against a production-adjacent platform, and a file nobody
// can read before it executes is a file nobody reviewed.

import { mkdirSync, readFileSync, readdirSync, writeFileSync, rmSync, existsSync } from 'node:fs'
import path from 'node:path'

import {
  JOURNAL_WRAPPER_DIR,
  buildAllJournalWrappers,
} from '../db/hosted/baseline-journal-wrapper'

const ROOT = path.resolve(import.meta.dirname, '..')

const read = (rel: string): string | null => {
  try {
    return readFileSync(path.join(ROOT, rel), 'utf8')
  } catch {
    return null
  }
}

function build() {
  const generated = buildAllJournalWrappers(read)
  if (generated.refusals.length > 0) {
    console.error('[journal] REFUSED — no wrapper written:')
    for (const r of generated.refusals) console.error(`  - ${r.unit} [${r.kind}] ${r.detail}`)
    process.exit(1)
  }
  return generated
}

function generate(): void {
  const generated = build()
  const dir = path.join(ROOT, JOURNAL_WRAPPER_DIR)
  // Remove stale wrappers: a wrapper for a unit the manifest no longer has is a
  // file an operator could still run, and it would insert a row `reconcileJournal`
  // then refuses as JOURNAL_CLAIMS_UNKNOWN_UNIT. Better it not exist.
  if (existsSync(dir)) {
    for (const f of readdirSync(dir)) {
      if (!Object.keys(generated.files).includes(`${JOURNAL_WRAPPER_DIR}/${f}`)) {
        rmSync(path.join(dir, f))
        console.log(`[journal] removed stale ${f}`)
      }
    }
  }
  mkdirSync(dir, { recursive: true })
  for (const [rel, content] of Object.entries(generated.files)) {
    writeFileSync(path.join(ROOT, rel), content, 'utf8')
  }
  console.log(`[journal] wrote ${Object.keys(generated.files).length} wrappers to ${JOURNAL_WRAPPER_DIR}/`)
  console.log(`[journal] apply order: ${generated.commands.length} commands, unit ZERO first`)
}

function verify(): void {
  const generated = build()
  const problems: string[] = []

  for (const [rel, expected] of Object.entries(generated.files)) {
    const onDisk = read(rel)
    if (onDisk === null) {
      problems.push(`${rel} is MISSING. Run \`pnpm journal:generate\`.`)
      continue
    }
    if (onDisk.replace(/\r\n?/g, '\n') !== expected) {
      problems.push(
        `${rel} DIVERGED from what the manifest and corpus produce. Do not edit a wrapper — ` +
          `it records the hash of the file it includes, and a hand edit is how a row that names one ` +
          `version comes to describe another.`,
      )
    }
  }

  const dir = path.join(ROOT, JOURNAL_WRAPPER_DIR)
  const extra = existsSync(dir)
    ? readdirSync(dir).filter((f) => !Object.keys(generated.files).includes(`${JOURNAL_WRAPPER_DIR}/${f}`))
    : []
  for (const f of extra) {
    problems.push(`${JOURNAL_WRAPPER_DIR}/${f} is not generated by anything. An extra runnable wrapper is an extra runnable unit.`)
  }

  if (problems.length > 0) {
    console.error('[journal] verification FAILED:')
    for (const p of problems) console.error(`  - ${p}`)
    process.exit(1)
  }
  console.log(`[journal] verification OK — all ${Object.keys(generated.files).length} wrappers regenerate byte-identically`)
}

const mode = process.argv[2]
if (mode === 'generate') generate()
else if (mode === 'verify') verify()
else {
  console.error('usage: tsx scripts/journal-artifacts.ts <generate|verify>')
  process.exit(2)
}
